/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner/index.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    Calendar: typeof import('./src/components/Calendar/index.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FillUp: typeof import('./src/components/FillUp/index.vue')['default']
    FormItem: typeof import('./src/components/FormItem/index.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/index.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle/index.vue')['default']
    Record: typeof import('./src/components/Record/index.vue')['default']
    RollingNumber: typeof import('./src/components/RollingNumber/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleInOut: typeof import('./src/components/ScaleInOut/index.vue')['default']
    Select: typeof import('./src/components/Select/index.vue')['default']
    StepFadeIn: typeof import('./src/components/StepFadeIn/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    Toggle: typeof import('./src/components/Toggle/index.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
  }
}
