export const MOCK_HOLIDAY = [
  {
    date: "2023/01/01",
    name: "元旦节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
  {
    date: "2023/01/01",
    name: "元旦节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
  {
    date: "2023/01/01",
    name: "元旦节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
  {
    date: "2023/01/01",
    name: "元旦节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
  {
    date: "2023/01/01",
    name: "元旦节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
  {
    date: "2023/10/01",
    name: "国庆节",
    typeId: "1",
    typeName: "放假",
    workWeight: 3,
    extraWeight: 3,
  },
];
