export type Area = {
  code: string; // 车牌后缀，如 'A', 'B' 等
  name: string; // 城市或地区名称
  remark: string; // 备注信息，可能为空字符串
};

export type ProvincePlate = {
  prefix: string; // 车牌省份前缀，如 '琼'
  province: string; // 省份名称，如 '海南省'
  area: Area[]; // 包含所有车牌后缀与对应地区的数组
};

export const provincePlateArray: ProvincePlate[] = [
  {
    prefix: "京",
    province: "北京市",
    area: [
      {
        code: "A",
        name: "东城区、西城区",
        remark: "核心城区号段，早期公务车辆较多",
      },
      {
        code: "B",
        name: "朝阳区",
        remark: "普通民用车辆为主，含CBD、望京等区域",
      },
      {
        code: "C",
        name: "丰台区",
        remark: "南部城区，居民及企事业车辆较多",
      },
      { code: "D", name: "石景山区", remark: "小型城区号段，数量有限" },
      {
        code: "E",
        name: "海淀区",
        remark: "科教与互联网企业聚集区，中关村、五道口",
      },
      { code: "F", name: "顺义区", remark: "机场、物流企业与郊区民用车" },
      { code: "G", name: "通州区", remark: "北京市行政副中心，较新号段" },
      { code: "H", name: "昌平区", remark: "沙河、回龙观、天通苑等地" },
      {
        code: "J",
        name: "大兴区",
        remark: "含亦庄开发区，注册车辆快速增长",
      },
      { code: "K", name: "房山区", remark: "部分区域进城受限" },
      { code: "L", name: "门头沟区", remark: "山区车辆为主" },
      { code: "M", name: "怀柔区", remark: "影视基地、旅游车辆较多" },
      { code: "N", name: "密云区", remark: "郊区县级号段" },
      { code: "P", name: "平谷区", remark: "郊区民用车为主" },
      { code: "Q", name: "延庆区", remark: "冬奥赛区，新增号段" },
      { code: "Y", name: "公安系统", remark: "公安、交警等警务车辆专用" },
      {
        code: "O",
        name: "外交与国际组织车辆",
        remark: "外交部统一管理，驻华使馆、国际机构使用",
      },
      {
        code: "V",
        name: "武警部队",
        remark: "武警系统专用号段，不对外发放",
      },
      {
        code: "Z",
        name: "中央军委及军区车辆",
        remark: "军用或特种用途车辆",
      },
    ],
  },
  {
    prefix: "沪",
    province: "上海市",
    area: [
      {
        code: "A",
        name: "黄浦区、静安区",
        remark: "早期中心城区号段，含外滩、南京路等核心区域",
      },
      {
        code: "B",
        name: "徐汇区、长宁区",
        remark: "南部核心城区，民用与企事业车辆较多",
      },
      {
        code: "C",
        name: "虹口区、杨浦区",
        remark: "东北城区号段，居民用车为主",
      },
      {
        code: "D",
        name: "浦东新区",
        remark: "原浦东、南汇、川沙地区，含陆家嘴与张江高科",
      },
      {
        code: "E",
        name: "闵行区",
        remark: "民用车辆号段，含莘庄、华漕等地区",
      },
      {
        code: "F",
        name: "宝山区",
        remark: "北部城区号段，含大场、顾村等",
      },
      {
        code: "G",
        name: "嘉定区",
        remark: "汽车工业集聚区，含安亭、江桥",
      },
      { code: "H", name: "上海市青浦区", remark: "西部郊区号段，靠近江苏昆山" },
      {
        code: "J",
        name: "松江区",
        remark: "南部新城，含大学城、车墩影视基地",
      },
      { code: "K", name: "金山区", remark: "沿海与工业区号段" },
      { code: "L", name: "奉贤区", remark: "南部郊区号段" },
      { code: "M", name: "崇明区", remark: "崇明岛区域车辆专用" },
      {
        code: "N",
        name: "公安系统",
        remark: "公安警务车辆专用，不对民用发放",
      },
      {
        code: "O",
        name: "外交与领事机构车辆",
        remark: "由外交部分配，驻沪领事馆车辆使用",
      },
      { code: "Q", name: "武警部队", remark: "武警与部队系统车辆专用" },
      {
        code: "R",
        name: "军区车辆",
        remark: "军队系统使用，不对民用发放",
      },
    ],
  },
  {
    prefix: "津",
    province: "天津市",
    area: [
      { code: "A", name: "天津市区", remark: "" },
      { code: "B", name: "天津市区", remark: "" },
      { code: "C", name: "天津市区", remark: "" },
      { code: "D", name: "天津市区", remark: "" },
      { code: "E", name: "天津市区", remark: "" },
    ],
  },
  {
    prefix: "渝",
    province: "重庆市",
    area: [
      {
        code: "A",
        name: "主城区",
        remark: "",
      },
      { code: "B", name: "永川区", remark: "" },
      { code: "C", name: "合川区", remark: "" },
      { code: "F", name: "江津区", remark: "" },
      { code: "G", name: "南川区", remark: "" },
      { code: "H", name: "綦江区", remark: "" },
    ],
  },
  {
    prefix: "冀",
    province: "河北省",
    area: [
      { code: "A", name: "石家庄市", remark: "" },
      { code: "B", name: "唐山市", remark: "" },
      { code: "C", name: "秦皇岛市", remark: "" },
      { code: "D", name: "邯郸市", remark: "" },
      { code: "E", name: "邢台市", remark: "" },
      { code: "F", name: "保定市", remark: "" },
      { code: "G", name: "张家口市", remark: "" },
      { code: "H", name: "承德市", remark: "" },
      { code: "J", name: "沧州市", remark: "" },
      { code: "R", name: "廊坊市", remark: "" },
      { code: "T", name: "衡水市", remark: "" },
    ],
  },
  {
    prefix: "晋",
    province: "山西省",
    area: [
      { code: "A", name: "太原市", remark: "" },
      { code: "B", name: "大同市", remark: "" },
      { code: "C", name: "阳泉市", remark: "" },
      { code: "D", name: "长治市", remark: "" },
      { code: "E", name: "晋城市", remark: "" },
      { code: "F", name: "朔州市", remark: "" },
      { code: "H", name: "忻州市", remark: "" },
      { code: "J", name: "吕梁市", remark: "" },
      { code: "K", name: "晋中市", remark: "" },
      { code: "L", name: "临汾市", remark: "" },
      { code: "M", name: "运城市", remark: "" },
    ],
  },
  {
    prefix: "蒙",
    province: "内蒙古自治区",
    area: [
      { code: "A", name: "呼和浩特市", remark: "" },
      { code: "B", name: "包头市", remark: "" },
      { code: "C", name: "乌海市", remark: "" },
      { code: "D", name: "赤峰市", remark: "" },
      { code: "E", name: "呼伦贝尔市", remark: "" },
      { code: "F", name: "兴安盟", remark: "" },
      { code: "G", name: "通辽市", remark: "" },
      { code: "H", name: "锡林郭勒盟", remark: "" },
      { code: "J", name: "乌兰察布市", remark: "" },
      { code: "K", name: "鄂尔多斯市", remark: "" },
      { code: "L", name: "巴彦淖尔市", remark: "" },
      { code: "M", name: "阿拉善盟", remark: "" },
    ],
  },
  {
    prefix: "辽",
    province: "辽宁省",
    area: [
      { code: "A", name: "沈阳市", remark: "" },
      { code: "B", name: "大连市", remark: "" },
      { code: "C", name: "鞍山市", remark: "" },
      { code: "D", name: "抚顺市", remark: "" },
      { code: "E", name: "本溪市", remark: "" },
      { code: "F", name: "丹东市", remark: "" },
      { code: "G", name: "锦州市", remark: "" },
      { code: "H", name: "营口市", remark: "" },
      { code: "J", name: "阜新市", remark: "" },
      { code: "K", name: "辽阳市", remark: "" },
      { code: "L", name: "盘锦市", remark: "" },
      { code: "M", name: "铁岭市", remark: "" },
      { code: "N", name: "朝阳市", remark: "" },
      { code: "P", name: "葫芦岛市", remark: "" },
    ],
  },
  {
    prefix: "吉",
    province: "吉林省",
    area: [
      { code: "A", name: "长春市", remark: "" },
      { code: "B", name: "吉林市", remark: "" },
      { code: "C", name: "四平市", remark: "" },
      { code: "D", name: "辽源市", remark: "" },
      { code: "E", name: "通化市", remark: "" },
      { code: "F", name: "白山市", remark: "" },
      { code: "G", name: "白城市", remark: "" },
      { code: "H", name: "延边朝鲜族自治州", remark: "" },
    ],
  },
  {
    prefix: "黑",
    province: "黑龙江省",
    area: [
      { code: "A", name: "哈尔滨市", remark: "" },
      { code: "B", name: "齐齐哈尔市", remark: "" },
      { code: "C", name: "牡丹江市", remark: "" },
      { code: "D", name: "佳木斯市", remark: "" },
      { code: "E", name: "大庆市", remark: "" },
      { code: "F", name: "伊春市", remark: "" },
      { code: "G", name: "鸡西市", remark: "" },
      { code: "H", name: "鹤岗市", remark: "" },
      { code: "J", name: "双鸭山市", remark: "" },
      { code: "K", name: "七台河市", remark: "" },
      { code: "L", name: "松花江地区（现归哈尔滨）", remark: "" },
      { code: "M", name: "黑河市", remark: "" },
      { code: "N", name: "绥化市", remark: "" },
      { code: "P", name: "大兴安岭地区", remark: "" },
    ],
  },
  {
    prefix: "苏",
    province: "江苏省",
    area: [
      { code: "A", name: "南京市", remark: "" },
      { code: "B", name: "无锡市", remark: "" },
      { code: "C", name: "徐州市", remark: "" },
      { code: "D", name: "常州市", remark: "" },
      { code: "E", name: "苏州市", remark: "" },
      { code: "F", name: "南通市", remark: "" },
      { code: "G", name: "连云港市", remark: "" },
      { code: "H", name: "淮安市", remark: "" },
      { code: "J", name: "盐城市", remark: "" },
      { code: "K", name: "扬州市", remark: "" },
      { code: "L", name: "镇江市", remark: "" },
      { code: "M", name: "泰州市", remark: "" },
      { code: "N", name: "宿迁市", remark: "" },
    ],
  },
  {
    prefix: "浙",
    province: "浙江省",
    area: [
      { code: "A", name: "杭州市", remark: "" },
      { code: "B", name: "宁波市", remark: "" },
      { code: "C", name: "温州市", remark: "" },
      { code: "D", name: "绍兴市", remark: "" },
      { code: "E", name: "湖州市", remark: "" },
      { code: "F", name: "嘉兴市", remark: "" },
      { code: "G", name: "金华市", remark: "" },
      { code: "H", name: "衢州市", remark: "" },
      { code: "J", name: "台州市", remark: "" },
      { code: "K", name: "丽水市", remark: "" },
      { code: "L", name: "舟山市", remark: "" },
    ],
  },
  {
    prefix: "皖",
    province: "安徽省",
    area: [
      { code: "A", name: "合肥市", remark: "" },
      { code: "B", name: "芜湖市", remark: "" },
      { code: "C", name: "蚌埠市", remark: "" },
      { code: "D", name: "淮南市", remark: "" },
      { code: "E", name: "马鞍山市", remark: "" },
      { code: "F", name: "淮北市", remark: "" },
      { code: "G", name: "铜陵市", remark: "" },
      { code: "H", name: "安庆市", remark: "" },
      { code: "J", name: "黄山市", remark: "" },
      { code: "K", name: "阜阳市", remark: "" },
      { code: "L", name: "宿州市", remark: "" },
      { code: "M", name: "滁州市", remark: "" },
      { code: "N", name: "六安市", remark: "" },
      { code: "P", name: "宣城市", remark: "" },
      { code: "R", name: "池州市", remark: "" },
      { code: "S", name: "亳州市", remark: "" },
    ],
  },
  {
    prefix: "闽",
    province: "福建省",
    area: [
      { code: "A", name: "福州市", remark: "" },
      { code: "B", name: "莆田市", remark: "" },
      { code: "C", name: "泉州市", remark: "" },
      { code: "D", name: "厦门市", remark: "" },
      { code: "E", name: "漳州市", remark: "" },
      { code: "F", name: "龙岩市", remark: "" },
      { code: "G", name: "三明市", remark: "" },
      { code: "H", name: "南平市", remark: "" },
      { code: "J", name: "宁德市", remark: "" },
    ],
  },
  {
    prefix: "赣",
    province: "江西省",
    area: [
      { code: "A", name: "南昌市", remark: "" },
      { code: "B", name: "赣州市", remark: "" },
      { code: "C", name: "宜春市", remark: "" },
      { code: "D", name: "吉安市", remark: "" },
      { code: "E", name: "上饶市", remark: "" },
      { code: "F", name: "抚州市", remark: "" },
      { code: "G", name: "九江市", remark: "" },
      { code: "H", name: "景德镇市", remark: "" },
      { code: "J", name: "萍乡市", remark: "" },
      { code: "K", name: "新余市", remark: "" },
      { code: "L", name: "鹰潭市", remark: "" },
    ],
  },
  {
    prefix: "鲁",
    province: "山东省",
    area: [
      { code: "A", name: "济南市", remark: "" },
      { code: "B", name: "青岛市", remark: "" },
      { code: "C", name: "淄博市", remark: "" },
      { code: "D", name: "枣庄市", remark: "" },
      { code: "E", name: "东营市", remark: "" },
      { code: "F", name: "烟台市", remark: "" },
      { code: "G", name: "潍坊市", remark: "" },
      { code: "H", name: "济宁市", remark: "" },
      { code: "J", name: "泰安市", remark: "" },
      { code: "K", name: "威海市", remark: "" },
      { code: "L", name: "日照市", remark: "" },
      { code: "M", name: "滨州市", remark: "" },
      { code: "N", name: "德州市", remark: "" },
      { code: "P", name: "聊城市", remark: "" },
      { code: "Q", name: "临沂市", remark: "" },
      { code: "R", name: "菏泽市", remark: "" },
    ],
  },
  {
    prefix: "豫",
    province: "河南省",
    area: [
      { code: "A", name: "郑州市", remark: "" },
      { code: "B", name: "开封市", remark: "" },
      { code: "C", name: "洛阳市", remark: "" },
      { code: "D", name: "平顶山市", remark: "" },
      { code: "E", name: "安阳市", remark: "" },
      { code: "F", name: "鹤壁市", remark: "" },
      { code: "G", name: "新乡市", remark: "" },
      { code: "H", name: "焦作市", remark: "" },
      { code: "J", name: "濮阳市", remark: "" },
      { code: "K", name: "许昌市", remark: "" },
      { code: "L", name: "漯河市", remark: "" },
      { code: "M", name: "三门峡市", remark: "" },
      { code: "N", name: "商丘市", remark: "" },
      { code: "P", name: "周口市", remark: "" },
      { code: "Q", name: "驻马店市", remark: "" },
      { code: "R", name: "南阳市", remark: "" },
      { code: "S", name: "信阳市", remark: "" },
      { code: "U", name: "济源市", remark: "" },
    ],
  },
  {
    prefix: "鄂",
    province: "湖北省",
    area: [
      { code: "A", name: "武汉市", remark: "" },
      { code: "B", name: "黄石市", remark: "" },
      { code: "C", name: "十堰市", remark: "" },
      { code: "D", name: "荆州市", remark: "" },
      { code: "E", name: "宜昌市", remark: "" },
      { code: "F", name: "襄阳市", remark: "" },
      { code: "G", name: "鄂州市", remark: "" },
      { code: "H", name: "荆门市", remark: "" },
      { code: "J", name: "黄冈市", remark: "" },
      { code: "K", name: "孝感市", remark: "" },
      { code: "L", name: "咸宁市", remark: "" },
      { code: "M", name: "仙桃市", remark: "" },
      { code: "N", name: "潜江市", remark: "" },
      { code: "P", name: "神农架林区", remark: "" },
      { code: "Q", name: "恩施土家族苗族自治州", remark: "" },
      { code: "R", name: "天门市", remark: "" },
    ],
  },
  {
    prefix: "湘",
    province: "湖南省",
    area: [
      { code: "A", name: "长沙市", remark: "" },
      { code: "B", name: "株洲市", remark: "" },
      { code: "C", name: "湘潭市", remark: "" },
      { code: "D", name: "衡阳市", remark: "" },
      { code: "E", name: "邵阳市", remark: "" },
      { code: "F", name: "岳阳市", remark: "" },
      { code: "G", name: "张家界市", remark: "" },
      { code: "H", name: "益阳市", remark: "" },
      { code: "J", name: "常德市", remark: "" },
      { code: "K", name: "娄底市", remark: "" },
      { code: "L", name: "郴州市", remark: "" },
      { code: "M", name: "永州市", remark: "" },
      { code: "N", name: "怀化市", remark: "" },
      { code: "U", name: "湘西土家族苗族自治州", remark: "" },
    ],
  },
  {
    prefix: "粤",
    province: "广东省",
    area: [
      { code: "A", name: "广州市", remark: "" },
      { code: "B", name: "深圳市", remark: "" },
      { code: "C", name: "珠海市", remark: "" },
      { code: "D", name: "汕头市", remark: "" },
      { code: "E", name: "佛山市", remark: "" },
      { code: "F", name: "韶关市", remark: "" },
      { code: "G", name: "湛江市", remark: "" },
      { code: "H", name: "肇庆市", remark: "" },
      { code: "J", name: "江门市", remark: "" },
      { code: "K", name: "茂名市", remark: "" },
      { code: "L", name: "惠州市", remark: "" },
      { code: "M", name: "梅州市", remark: "" },
      { code: "N", name: "汕尾市", remark: "" },
      { code: "P", name: "河源市", remark: "" },
      { code: "Q", name: "阳江市", remark: "" },
      { code: "R", name: "清远市", remark: "" },
      { code: "S", name: "东莞市", remark: "" },
      { code: "T", name: "中山市", remark: "" },
      { code: "U", name: "潮州市", remark: "" },
      { code: "V", name: "揭阳市", remark: "" },
      { code: "W", name: "云浮市", remark: "" },
    ],
  },
  {
    prefix: "桂",
    province: "广西壮族自治区",
    area: [
      { code: "A", name: "南宁市", remark: "" },
      { code: "B", name: "柳州市", remark: "" },
      { code: "C", name: "桂林市", remark: "" },
      { code: "D", name: "梧州市", remark: "" },
      { code: "E", name: "北海市", remark: "" },
      { code: "F", name: "防城港市", remark: "" },
      { code: "G", name: "钦州市", remark: "" },
      { code: "H", name: "贵港市", remark: "" },
      { code: "J", name: "玉林市", remark: "" },
      { code: "K", name: "百色市", remark: "" },
      { code: "L", name: "贺州市", remark: "" },
      { code: "M", name: "河池市", remark: "" },
      { code: "N", name: "来宾市", remark: "" },
      { code: "P", name: "崇左市", remark: "" },
    ],
  },
  {
    prefix: "琼",
    province: "海南省",
    area: [
      { code: "A", name: "海口市", remark: "" },
      { code: "B", name: "三亚市", remark: "" },
      { code: "C", name: "琼海市", remark: "" },
      { code: "D", name: "儋州市", remark: "" },
      { code: "E", name: "文昌市", remark: "" },
      { code: "F", name: "万宁市", remark: "" },
      { code: "G", name: "东方市", remark: "" },
      { code: "H", name: "五指山市", remark: "" },
    ],
  },
  {
    prefix: "川",
    province: "四川省",
    area: [
      {
        code: "A",
        name: "成都市",
        remark:
          "四川省辖地级市、省会、副省级市、超大城市，地处中国西南部、四川盆地西部、青藏高原东缘，成都平原腹心，属亚热带季风气候，总面积14335平方千米，通用语言为西南官话。",
      },
      {
        code: "B",
        name: "绵阳市",
        remark:
          "四川省辖地级市，省域副中心城市，Ⅱ型大城市， 三线城市， 是中国唯一科技城， 中国野生大熊猫第一市， [289]位于四川盆地西北部，涪江中上游地带。",
      },
      { code: "C", name: "自贡市", remark: "" },
      { code: "D", name: "攀枝花市", remark: "" },
      { code: "E", name: "泸州市", remark: "" },
      { code: "F", name: "德阳市", remark: "" },
      { code: "G", name: "成都市", remark: "" },
      { code: "H", name: "广元市", remark: "" },
      { code: "J", name: "遂宁市", remark: "" },
      { code: "K", name: "内江市", remark: "" },
      { code: "L", name: "乐山市", remark: "" },
      { code: "M", name: "资阳市", remark: "" },
      { code: "Q", name: "宜宾市", remark: "" },
      { code: "R", name: "南充市", remark: "" },
      { code: "S", name: "达州市", remark: "" },
      { code: "T", name: "雅安市", remark: "" },
      { code: "U", name: "阿坝藏族羌族自治州", remark: "" },
      { code: "V", name: "甘孜藏族自治州", remark: "" },
      { code: "W", name: "凉山彝族自治州", remark: "" },
      { code: "X", name: "广安市", remark: "" },
      { code: "Y", name: "巴中市", remark: "" },
      { code: "Z", name: "眉山市", remark: "" },
    ],
  },
  {
    prefix: "贵",
    province: "贵州省",
    area: [
      { code: "A", name: "贵阳市", remark: "" },
      { code: "B", name: "六盘水市", remark: "" },
      { code: "C", name: "遵义市", remark: "" },
      { code: "D", name: "安顺市", remark: "" },
      { code: "E", name: "毕节市", remark: "" },
      { code: "F", name: "铜仁市", remark: "" },
      { code: "G", name: "黔西南布依族苗族自治州", remark: "" },
      { code: "H", name: "黔东南苗族侗族自治州", remark: "" },
      { code: "J", name: "黔南布依族苗族自治州", remark: "" },
    ],
  },
  {
    prefix: "云",
    province: "云南省",
    area: [
      { code: "A", name: "昆明市", remark: "" },
      { code: "B", name: "东川区", remark: "" },
      { code: "C", name: "昭通市", remark: "" },
      { code: "D", name: "曲靖市", remark: "" },
      { code: "E", name: "楚雄彝族自治州", remark: "" },
      { code: "F", name: "玉溪市", remark: "" },
      { code: "G", name: "红河哈尼族彝族自治州", remark: "" },
      { code: "H", name: "文山壮族苗族自治州", remark: "" },
      { code: "J", name: "普洱市", remark: "" },
      { code: "K", name: "西双版纳傣族自治州", remark: "" },
      { code: "L", name: "大理白族自治州", remark: "" },
      { code: "M", name: "保山市", remark: "" },
      { code: "N", name: "德宏傣族景颇族自治州", remark: "" },
      { code: "P", name: "丽江市", remark: "" },
      { code: "Q", name: "怒江傈僳族自治州", remark: "" },
      { code: "R", name: "迪庆藏族自治州", remark: "" },
      { code: "S", name: "临沧市", remark: "" },
    ],
  },
  {
    prefix: "藏",
    province: "西藏自治区",
    area: [
      { code: "A", name: "拉萨市", remark: "" },
      { code: "B", name: "昌都市", remark: "" },
      { code: "C", name: "山南市", remark: "" },
      { code: "D", name: "日喀则市", remark: "" },
      { code: "E", name: "那曲市", remark: "" },
      { code: "F", name: "阿里地区", remark: "" },
      { code: "G", name: "林芝市", remark: "" },
    ],
  },
  {
    prefix: "陕",
    province: "陕西省",
    area: [
      { code: "A", name: "西安市", remark: "" },
      { code: "B", name: "铜川市", remark: "" },
      { code: "C", name: "宝鸡市", remark: "" },
      { code: "D", name: "咸阳市", remark: "" },
      { code: "E", name: "渭南市", remark: "" },
      { code: "F", name: "汉中市", remark: "" },
      { code: "G", name: "安康市", remark: "" },
      { code: "H", name: "商洛市", remark: "" },
      { code: "J", name: "延安市", remark: "" },
      { code: "K", name: "榆林市", remark: "" },
    ],
  },
  {
    prefix: "甘",
    province: "甘肃省",
    area: [
      { code: "A", name: "兰州市", remark: "" },
      { code: "B", name: "嘉峪关市", remark: "" },
      { code: "C", name: "金昌市", remark: "" },
      { code: "D", name: "白银市", remark: "" },
      { code: "E", name: "天水市", remark: "" },
      { code: "F", name: "酒泉市", remark: "" },
      { code: "G", name: "张掖市", remark: "" },
      { code: "H", name: "武威市", remark: "" },
      { code: "J", name: "定西市", remark: "" },
      { code: "K", name: "陇南市", remark: "" },
      { code: "L", name: "平凉市", remark: "" },
      { code: "M", name: "庆阳市", remark: "" },
      { code: "N", name: "临夏回族自治州", remark: "" },
      { code: "P", name: "甘南藏族自治州", remark: "" },
    ],
  },
  {
    prefix: "青",
    province: "青海省",
    area: [
      { code: "A", name: "西宁市", remark: "" },
      { code: "B", name: "海东市", remark: "" },
      { code: "C", name: "海北藏族自治州", remark: "" },
      { code: "D", name: "黄南藏族自治州", remark: "" },
      { code: "E", name: "海南藏族自治州", remark: "" },
      { code: "F", name: "果洛藏族自治州", remark: "" },
      { code: "G", name: "玉树藏族自治州", remark: "" },
      { code: "H", name: "海西蒙古族藏族自治州", remark: "" },
    ],
  },
  {
    prefix: "宁",
    province: "宁夏回族自治区",
    area: [
      { code: "A", name: "银川市", remark: "" },
      { code: "B", name: "石嘴山市", remark: "" },
      { code: "C", name: "吴忠市", remark: "" },
      { code: "D", name: "固原市", remark: "" },
      { code: "E", name: "中卫市", remark: "" },
    ],
  },
  {
    prefix: "新",
    province: "新疆维吾尔自治区",
    area: [
      { code: "A", name: "乌鲁木齐市", remark: "" },
      { code: "B", name: "昌吉回族自治州", remark: "" },
      { code: "C", name: "石河子市", remark: "" },
      { code: "D", name: "奎屯市", remark: "" },
      { code: "E", name: "博尔塔拉蒙古自治州", remark: "" },
      { code: "F", name: "伊犁哈萨克自治州", remark: "" },
      { code: "G", name: "塔城地区", remark: "" },
      { code: "H", name: "阿勒泰地区", remark: "" },
      { code: "J", name: "克拉玛依市", remark: "" },
      { code: "K", name: "吐鲁番市", remark: "" },
      { code: "L", name: "哈密市", remark: "" },
      { code: "M", name: "巴音郭楞蒙古自治州", remark: "" },
      { code: "N", name: "阿克苏地区", remark: "" },
      { code: "P", name: "克孜勒苏柯尔克孜自治州", remark: "" },
      { code: "Q", name: "喀什地区", remark: "" },
      { code: "R", name: "和田地区", remark: "" },
      { code: "S", name: "阿拉尔市", remark: "" },
      { code: "T", name: "图木舒克市", remark: "" },
      { code: "U", name: "五家渠市", remark: "" },
      { code: "V", name: "铁门关市", remark: "" },
    ],
  },
];
