/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FillUp: typeof import('./components/FillUp/index.vue')['default']
    Form: typeof import('./components/Form/index.vue')['default']
    FormItem: typeof import('./components/FormItem/index.vue')['default']
    MenuItem: typeof import('./components/MenuItem/index.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer/index.vue')['default']
    RollingNumber: typeof import('./components/RollingNumber/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleInOut: typeof import('./components/ScaleInOut/index.vue')['default']
    StepFadeIn: typeof import('./components/StepFadeIn/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
    Typewriter: typeof import('./components/Typewriter/index.vue')['default']
    UploadExcel: typeof import('./components/UploadExcel/index.vue')['default']
  }
}
