/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner/index.vue')['default']
    Button: typeof import('./components/Button/index.vue')['default']
    Calendar: typeof import('./components/Calendar/index.vue')['default']
    DatePicker: typeof import('./components/DatePicker/index.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FillUp: typeof import('./components/FillUp/index.vue')['default']
    FormItem: typeof import('./components/FormItem/index.vue')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    Input: typeof import('./components/Input/index.vue')['default']
    MenuItem: typeof import('./components/MenuItem/index.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer/index.vue')['default']
    PageTitle: typeof import('./components/PageTitle/index.vue')['default']
    Record: typeof import('./components/Record/index.vue')['default']
    RollingNumber: typeof import('./components/RollingNumber/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleInOut: typeof import('./components/ScaleInOut/index.vue')['default']
    Select: typeof import('./components/Select/index.vue')['default']
    StepFadeIn: typeof import('./components/StepFadeIn/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
    Toggle: typeof import('./components/Toggle/index.vue')['default']
    Typewriter: typeof import('./components/Typewriter/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
  }
}
